name: Notify Microsoft 365
on: [push] # 이벤트를 변경하여 다른 GitHub 이벤트에 대응하게 할 수 있습니다.
           # push 이벤트가 발생할 때마다 이 workflow가 실행되도록 설정합니다. GitHub에서는 push, 
           # pull request, issue comment 등 다양한 이벤트를 통해 workflow를 트리거할 수 있습니다.
jobs:
 notify:
   runs-on: ubuntu-latest  # 작업 환경:작업이 최신 Ubuntu 가상 환경에서 실행됨을 의미합니다.
   steps:
     - name: Send notification to Microsoft 365
       run: |
        curl -H "Content-Type: application/json" -d "{'text':'이채진의 새로운 커밋'}" https://o365kopo.webhook.office.com/webhookb2/7bfe4d1f-d041-4708-b64a-be6d49f884a4@ad21525c-fc0f-4dbc-a403-67ce00add0e4/IncomingWebhook/bf106be5c5804d36a124c6a27807454e/60bd78a8-d56b-479c-a3ce-1345a15dc0ec
        # ( curl 로 incoming webhook을 호출) 보내고 싶은 메시지를 설정하면 된다.
